config/routes.rb
KrazyChat::Application.routes.draw do
  scope via: :all do
    match '/health_check' => 'monitor#health_check'
    match '/me', to: 'users#me', as: 'me'
    match '/users', to: 'users#index', as: 'users'
    match '/users/username_status', to: 'users#username_status', as: 'check_username_status'
    match '/users/create_unregistered', to: 'users#create_unregistered', as: 'create_unregistered_user'
    match '/users/create', to: 'users#create', as: 'create_user'
    match '/users/update', to: 'users#update', as: 'update_user'
    match '/accounts/update', to: 'accounts#update', as: 'update_account'
    match '/password/reset_email' => 'accounts#send_reset_email', as: 'send_reset_email'
    match '/password/reset_sms' => 'accounts#send_reset_sms', as: 'send_reset_sms'
    match '/password/reset/:token' => 'accounts#reset_password', :as => 'reset_password'

    match '/preferences/update', to: 'user_preferences#update', as: 'update_user_preferences'
    match '/ios_device_preferences/update', to: 'device_preferences#update', as: 'update_ios_device_preferences'
    match '/android_device_preferences/update', to: 'device_preferences#update', as: 'update_android_device_preferences'
    match '/groups/:group_id/user_group_preferences', to: 'user_group_preferences#show', as: 'show_user_group_preferences'
    match '/groups/:group_id/user_group_preferences/update', to: 'user_group_preferences#update', as: 'update_user_group_preferences'

    match '/login', to: 'sessions#create', as: 'login'
    match '/logout', to: 'sessions#destroy', as: 'logout'
    match '/checkin', to: 'checkin#index', as: 'checkin'

    match '/conversations', to: 'conversations#index', as: 'conversations'

    match '/groups/create', to: 'groups#create', as: 'create_group'
    match '/groups/:id/update', to: 'groups#update', as: 'update_group'
    match '/groups/join/:join_code', to: 'groups#join', as: 'join_group'
    match '/groups/:id/leave', to: 'groups#leave', as: 'leave_group'

    match '/groups/:group_id/messages/create', to: 'group_messages#create', as: 'create_group_message'
    match '/groups/:group_id/messages', to: 'group_messages#index', as: 'group_messages'

    match '/groups/find', to: 'groups#find', as: 'find_group'
    match '/groups/:id', to: 'groups#show', as: 'show_group'
    match '/groups/:id/is_member', to: 'groups#is_member', as: 'is_member_group'

    match '/groups/:id/banned_users', to: 'banned_group_users#index', as: 'banned_group_users'
    match '/groups/:id/ban', to: 'banned_group_users#create', as: 'ban_group_user'
    match '/groups/:id/unban', to: 'banned_group_users#destroy', as: 'unban_group_user'

    match '/one_to_ones/:id', to: 'one_to_ones#show', as: 'one_to_one'
    match '/one_to_ones/:id/update', to: 'one_to_ones#update', as: 'update_one_to_one'
    match '/one_to_ones/:one_to_one_id/messages/create', to: 'one_to_one_messages#create', as: 'create_one_to_one_message'
    match '/one_to_ones/:one_to_one_id/messages', to: 'one_to_one_messages#index', as: 'one_to_one_messages'

    match '/messages/create', to: 'messages#create', as: 'create_message'
    match '/messages/:id/delete', to: 'messages#delete', as: 'delete_message'
    match '/messages/:id/export', to: 'messages#export', as: 'export_message'

    match '/messages/:id/likes', to: 'message_likes#index', as: 'message_likes'
    match '/messages/:id/like', to: 'message_likes#create', as: 'like_message'
    match '/messages/:id/unlike', to: 'message_likes#destroy', as: 'unlike_message'

    match '/faye_clients/:id/update', to: 'faye_clients#update', as: 'update_faye_client'

    match '/ios/apn/set', to: 'ios/apn#set', as: 'set_apn'
    match '/ios/apn/reset', to: 'ios/apn#reset', as: 'reset_apn'

    match '/android/gcm/set', to: 'android/gcm#set', as: 'set_gcm'
    match '/android/gcm/reset', to: 'android/gcm#reset', as: 'reset_gcm'

    match '/blocked_users', to: 'blocked_users#index', as: 'blocked_users'
    match '/users/:id/block', to: 'blocked_users#create', as: 'block_user'
    match '/users/:id/unblock', to: 'blocked_users#destroy', as: 'unblock_user'
    match '/users/:id/avatar_image/flag', to: 'user_avatar_images#flag', as: 'flag_avatar_image'
    match '/users/:id/avatar_video/flag', to: 'user_avatar_videos#flag', as: 'flag_avatar_video'
    match '/users/:id/flag', to: 'users#flag', as: 'flag_user'

    match '/emails', to: 'emails#index', as: 'emails'
    match '/emails/create', to: 'emails#create', as: 'create_email'
    match '/emails/:id/update', to: 'emails#update', as: 'update_email'
    match '/emails/:id/destroy', to: 'emails#destroy', as: 'destroy_email'

    match '/phones/create', to: 'phones#create', as: 'create_phone'
    match '/phones/verify', to: 'phones#verify', as: 'verify_phone'
    match '/phones/add', to: 'phones#add', as: 'add_phones'
    match '/phones/confirm_activation', to: 'phones#confirm_activation', as: 'confirm_phone_activation'

    match '/contacts', to: 'contacts#index', as: 'contacts'
    match '/contacts/add', to: 'contacts#add', as: 'add_contacts'
    match '/contacts/remove', to: 'contacts#remove', as: 'remove_contacts'
    match '/contacts/autoconnect', to: 'contacts#autoconnect', as: 'remove_autoconnect'
    match '/groups/:id/add_users', to: 'groups#add_users', as: 'groups_add_users'

    match '/moderation/callback', to: 'moderation#callback', as: 'moderation_callback'

    match '/hook/callback', to: 'hook#callback', as: 'hook_callback'

    match '/admin', to: 'admin#app_reviews', as: 'admin'
    match '/admin/login', to: 'admin_auth#login', as: 'admin_login'
    match '/admin/logout', to: 'admin_auth#logout', as: 'admin_logout'
    match '/admin/forgot_password', to: 'admin_auth#forgot_password', as: 'admin_forgot_password'
    match '/admin/send_reset_password_email', to: 'admin_auth#send_reset_password_email', as: 'admin_send_reset_password_email'
    match '/admin/reset_password', to: 'admin_auth#update_password', as: 'admin_update_password', via: [:post, :put]
    match '/admin/reset_password', to: 'admin_auth#reset_password', as: 'admin_reset_password'
    match '/admin/sms_stats', to: 'admin#sms_stats', as: 'admin_sms_stats'
    match '/admin/cohort_metrics', to: 'admin#cohort_metrics', as: 'admin_cohort_metrics'
    match '/admin/users', to: 'admin#users', as: 'admin_users'
    match '/admin/users/:id', to: 'admin#show_user', as: 'admin_user'
    match '/admin/users/:id/friends', to: 'admin#show_user_friends', as: 'admin_user_friends'
    match '/admin/settings', to: 'admin#settings', as: 'admin_settings'
    match '/admin/settings/:key/edit', to: 'admin#edit_setting', as: 'admin_edit_setting'
    match '/admin/settings/:key/update', to: 'admin#update_setting', as: 'admin_update_setting'
    match '/admin/app_reviews', to: 'admin#app_reviews', as: 'admin_app_reviews'
    match '/admin/bot_messages', to: 'admin#bot_messages', as: 'admin_bot_messages'
    match '/admin/users/:id/ban', to: 'admin#ban_user', as: 'admin_ban_user'
    match '/admin/users/:id/unban', to: 'admin#unban_user', as: 'admin_unban_user'

    match '/logs/event', to: 'logs#event', as: 'logs_event'

    match '/snaps/fetched', to: 'snaps#fetched', as: 'fetched_snaps'

    match '/stories/search', to: 'stories#search', as: 'search_stories'
    match '/public_feed', to: 'public_feed#index', as: 'public_feed'
    match '/friend_feed', to: 'friend_feed#index', as: 'friend_feed'
    match '/stories/tags/:tag', to: 'stories#tagged', as: 'tagged_stories'
    match '/users/:id/stories', to: 'stories_lists#show', as: 'stories_list'
    match '/stories/:id', to: 'stories#show', as: 'show_story'
    match '/stories/:id/update', to: 'stories#update', as: 'update_story'
    match '/stories/:id/likes', to: 'story_likes#index', as: 'story_likes'
    match '/stories/:id/like', to: 'story_likes#create', as: 'like_story'
    match '/stories/:id/export', to: 'stories#export', as: 'export_story'
    match '/stories/:id/delete', to: 'stories#delete', as: 'delete_story'
    match '/stories/:id/flag', to: 'stories#flag', as: 'flag_story'

    match '/friends', to: 'friends#index', as: 'friends'
    match '/friends/add', to: 'friends#add', as: 'add_friends'
    match '/friends/remove', to: 'friends#remove', as: 'remove_friends'

    match '/blacklisted_usernames/add', to: 'blacklisted_usernames#add', as: 'add_blacklisted_username'
    match '/app_reviews/create', to: 'app_reviews#create', as: 'create_app_review'
  end

  require 'sidekiq/web'
  mount Sidekiq::Web, at: '/sidekiq'

  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == Rails.configuration.app['admin']['username'] &&
      password == Rails.configuration.app['admin']['password']
  end
end

app/views/admin/app_reviews.html.erb
<style>
table tr th { text-align: center; }
table tr td { text-align: center; }
table tr td.feedback { text-align: left; }
</style>


<div class='admin-content'>
<h1>App Reviews</h1>


<table class="table table-striped table-bordered" style="width: 800px;">
  <tr>
    <th>ID</th>
    <th>User ID</th>
    <th>Username</th>
    <th>Rating</th>
    <th>Feedback</th>
    <th>Will Write Review?</th>
    <th style="width: 140px">Created At (EST)</th>
  </tr>

  <% @app_reviews.each do |r| %>
  <tr>
    <td><%= r.id %></td>
    <td><%= link_to(r.user.id, admin_user_path(r.user)) if r.user %></td>
    <td><%= link_to(r.user.try(:username), admin_user_path(r.user)) if r.user %></td>
    <td><%= r.rating %></td>
    <td class="feedback"><%= r.feedback %></td>
    <td><%= r.will_write_review %></td>
    <td><%= admin_timestamp(r.created_at, format: :short) %></td>
  </tr>
  <% end %>
</table>


<%= page_entries_info @app_reviews %><br />
<%= paginate @app_reviews %>

app/views/admin/bot_messages.html.erb
<style>
table tr th, table tr td { text-align: center; }
table tr td.text { text-align: left; }
</style>


<div class='admin-content'>
<h1>Bot Messages</h1>


<table class="table table-striped table-bordered" style="width: 800px;">
  <tr>
    <th>ID</th>
    <th>User ID</th>
    <th>Username</th>
    <th>Text</th>
    <th>Attachment</th>
    <th style="width: 140px">Created At (EST)</th>
  </tr>

  <% @bot_messages.each do |m| %>
  <tr>
    <td><%= m.id %></td>
    <td><%= link_to(m.user.id, admin_user_path(m.user)) if m.user %></td>
    <td><%= link_to(m.user.try(:username), admin_user_path(m.user)) if m.user %></td>
    <td class="text"><%= m.text %></td>
    <td class="attachment">
      <% if m.attachment_url.to_s.ends_with?('.mp4') %>
        <video width="169" controls>
          <source src="<%= m.attachment_url.sub('http:', 'https:') %>">
        </video>
      <% elsif m.attachment_preview_url.present? %>
        <%= image_tag(m.attachment_preview_url.sub('http:', 'https:')) %>
      <% end -%>
    </td>
    <td><%= admin_timestamp(m.created_at, format: :short) %></td>
  </tr>
  <% end %>
</table>


<%= page_entries_info @bot_messages %><br />
<%= paginate @bot_messages %>

app/views/admin/cohort_metrics.html.erb
<style>
  table.retention, p.explanation { width: 850px; }
  th, td { text-align: center; }
  th.day, td.percentage { width: 50px; }
  th.registered { width: 132px; }
</style>


<div class="container">
<h1>Cohort Metrics (Eastern Time)</h1>


<h2>Avg. Percentage of a User's Snapchat Friends Who are Registered</h2>

<p class="explanation text-muted">
  For each user who registered on a given date Y (first column) *and* came to the app on a given date X (first row), what percentage of his Snapchat friends are registered in SCP?
  Each user's percentage for a given registration and action date is calculated, and then those percentages are averaged.<br /><br />
  Note:
  <% if @friend_counts_in_progress -%>
    This table is currently being re-calculated. Please refresh in a few minutes.
  <% else -%>
    This table is cached and will be re-calculated in <%= distance_of_time_in_words(@admin_metrics.next_recalculation_at - Time.current) %>.
  <% end -%>
</p>


<table class="retention table table-striped table-bordered">
  <tr>
    <th class="registered">Registered</th>
    <th colspan="<%= @days %>">Days Later</th>
  </tr>

  <tr>
    <th />

    <% @days.times do |days_later| %>
      <th class="day"><%= days_later %></th>
    <% end -%>
  </tr>

  <% (@days - 1).downto(0) do |i| %>
    <% registered_date = @today - i %>
    <tr>
      <th><%= registered_date %></th>

      <% @days.times do |j| %>
        <% action_date = registered_date + j %>

        <td class="percentage">
          <% if action_date <= @today -%>
            <% percentages = [] %>
            <% ((@friend_counts[registered_date.to_s] || {})[action_date.to_s] || []).each do |user_id, hsh| -%>
              <% percentages << hsh['percent_registered'] %>
            <% end -%>
            <% percentages.compact! %>
            <% avg = percentages.sum / percentages.size if percentages.present? %>
            <%= avg.nil? ? '-' : avg.round.to_s + '%' -%>
          <% end -%>
        </td>
      <% end -%>
    </tr>
    <% end -%>
</table>


<br /><br />
<h2>Percentage of Sent Messages to SCP Recipients</h2>

<p class="explanation text-muted">
  Of all the messages sent on a given date X (first row) by users who registered on a given date Y (first column), what percentage of the recipients are registered in SCP (as opposed to Snapchat-only recipients)?
</p>


<table class="retention table table-striped table-bordered">
  <tr>
    <th class="registered">Registered</th>
    <th colspan="<%= @days %>">Days Later</th>
  </tr>

  <tr>
    <th />

    <% @days.times do |days_later| %>
      <th class="day"><%= days_later %></th>
    <% end -%>
  </tr>

  <% (@days - 1).downto(0) do |i| %>
    <% registered_date = @today - i %>
    <tr>
      <th><%= registered_date %></th>

      <% @days.times do |j| %>
        <% action_date = registered_date + j %>

        <td class="percentage">
          <% if action_date <= @today -%>
            <% percentage = (@sent["registered_on_#{registered_date}"] || {})["action_on_#{action_date}"] -%>
            <%= percentage.nil? ? '-' : percentage.round.to_s + '%' -%>
          <% end -%>
        </td>
      <% end -%>
    </tr>
    <% end -%>
</table>


<br /><br />
<h2>Percentage of Received Messages from SCP Senders</h2>

<p class="explanation text-muted">
  Of all the messages received on a given date X (first row) by users who registered on a given date Y (first column), what percentage of the senders are registered in SCP (as opposed to a Snapchat-only senders who sent from Snapchat)?
</p>


<table class="retention table table-striped table-bordered">
  <tr>
    <th class="registered">Registered</th>
    <th colspan="<%= @days %>">Days Later</th>
  </tr>

  <tr>
    <th />

    <% @days.times do |days_later| %>
      <th><%= days_later %></th>
    <% end -%>
  </tr>

  <% (@days - 1).downto(0) do |i| %>
    <% registered_date = @today - i %>
    <tr>
      <th><%= registered_date %></th>

      <% @days.times do |j| %>
        <% action_date = registered_date + j %>

        <% if action_date > @today %>
          <td />
        <% else -%>
          <% percentage = (@received["registered_on_#{registered_date}"] || {})["action_on_#{action_date}"] %>
          <td><%= percentage.nil? ? '-' : percentage.round.to_s + '%' %></td>
        <% end -%>
      <% end -%>
    </tr>
    <% end -%>
</table>

</div>

app/views/admin/edit_setting.html.erb
<div class='admin-content'>

<form method='post' action='<%= admin_update_setting_path %>' style='margin: 20px 0'>
  <h1>Edit Setting</h1>
  Note: When specifying a list, separate items with a comma.<br /><br />

  <div class='form-group'>
    <label for='value'><%= @key %></label>
    <input type='text' name='value' id='value' value='<%= @value %>' class='form-control' style='width: 300px'>
  </div>
  <div>
    <button type='submit' class='btn btn-primary'>Save</button>
  </div>
</form>

app/views/admin/settings.html.erb
<div class='admin-content'>
<h1>Settings</h1>


<table class="table table-striped table-bordered" style="width: 600px;">
  <tr>
    <th style="text-align: center;">Key</th>
    <th style="text-align: center;">Value</th>
  </tr>

  <% @settings.each do |key, value| %>
  <tr>
    <td align="center"><%= key %></td>
    <td align="center"><%= value.presence %></td>
    <td align="center"><%= link_to('Edit', admin_edit_setting_url(key)) %></td>
  </tr>
  <% end %>
</table>

app/views/admin/show_user.html.erb
<div class='admin-content'>

<div class='nav'>
  <%= link_to 'Back to Users', admin_users_path %>
</div>

<h3><%= @user.username %></h3>

<div>created: <%= admin_timestamp @user.created_at, time_ago: true %></div>
<div>
  emails:
  <%= @user.emails.pluck(:email).map {|e| mail_to(e, e) }.join(', ').html_safe %>
</div>
<% if @user.avatar_image %>
  <div><%= image_tag @user.avatar_url %></div>
<% end %>
<% if @user.avatar_video %>
  <div>
    <video controls>
      <source src='<%= @user.avatar_video_url %>'>
    </video>
  </div>
<% end %>
<% if @user.account.one_to_one_wallpaper_image %>
  <div><%= link_to '1-1 wallpaper', @user.account.one_to_one_wallpaper_url, target: '_blank' %></div>
<% end %>

<table class='table table-striped'>
  <tbody>
    <tr>
      <td>friends</td>
      <td>
        <%= @user.friend_ids.size %>
        <%= link_to 'See All', admin_user_friends_path(@user) %>
      </td>
    </tr>
  </tbody>
</table>

<div>
  This user...
  <table class='table table-striped'>
    <tbody>
      <tr>
        <td>was invited by another user?</td><td><%= "#{@user.invited?}".titleize %></td>
      </tr>
      <tr>
        <td>is deactivated?</td><td><%= "#{@user.deactivated}".titleize %></td>
      </tr>
    </tbody>
  </table>
</div>

<div>
  <% if @user.banned? %>
    <%= button_to 'Unban User', admin_unban_user_url(@user) %>
  <% else %>
    <%= button_to 'Ban User', admin_ban_user_url(@user) %>
  <% end -%>
</div>

</div>

app/views/admin/show_user_contacts.html.erb
<div class='admin-content'>

<div class='nav'>
  <%= link_to 'Users', admin_users_path %>
  &gt;
  <%= link_to @user.username, admin_user_path(@user) %>
  &gt;
  Contacts
</div>

<h3><%= @user.username %>'s Contacts</h3>

<% if @contacts.size > 0 %>
  <table class='table table-striped'>
    <tbody>
      <% @contacts.each do |user| %>
        <tr>
          <td><%= link_to user.username, admin_user_path(user) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>
    None Found.
  </p>
<% end %>

<ul class='pagination'>
  <% if @offset > 0 %>
    <li><%= link_to 'First', admin_user_contacts_path(@user) %></li>
  <% end %>
  <% if @offset > 0 %>
    <li><%= link_to 'Previous', admin_user_contacts_path(@user, offset: @offset - @contacts.size) %></li>
  <% end %>
  <% if @offset + @contacts.size < @contacts_count %>
    <li><%= link_to 'Next', admin_users_path(@user, offset: @offset + @contacts_size) %></li>
  <% end %>
</ul>

</div>

app/views/admin/show_user_friends.html.erb
<div class='admin-content'>

<div class='nav'>
  <%= link_to 'Users', admin_users_path %>
  &gt;
  <%= link_to @user.username, admin_user_path(@user) %>
  &gt;
  friends
</div>

<h3><%= @user.username %>'s friends</h3>

<% if @friends.size > 0 %>
  <table class='table table-striped'>
    <tbody>
      <% @friends.each do |user| %>
        <tr>
          <td><%= link_to user.username, admin_user_path(user) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>
    None Found.
  </p>
<% end %>

<ul class='pagination'>
  <% if @offset > 0 %>
    <li><%= link_to 'First', admin_user_friends_path(@user) %></li>
  <% end %>
  <% if @offset > 0 %>
    <li><%= link_to 'Previous', admin_user_friends_path(@user, offset: @offset - @friends.size) %></li>
  <% end %>
  <% if @offset + @friends.size < @friends_count %>
    <li><%= link_to 'Next', admin_user_friends_path(@user, offset: @offset + @friends.size) %></li>
  <% end %>
</ul>

</div>

app/views/admin/sms_stats.html.erb
<div class='admin-content'>
<h1>SMS Stats</h1>


<h2>All Time</h2>

<table class="table table-striped table-bordered" style="width: 300px;">
  <tr>
    <th style="text-align: center;">Sent</th>
    <th style="text-align: center;">Received</th>
    <th style="text-align: center;">Errors</th>
  </tr>

  <tr>
    <td align="center"><%= number_with_delimiter(@all_time_sent_sms_count.to_i) %></td>
    <td align="center"><%= number_with_delimiter(@all_time_received_sms_count.to_i) %></td>
    <td align="center"><%= number_with_delimiter(@all_time_error_count.to_i) %></td>
  </tr>
</table>


<h2>Monthly</h2>

<table class="table table-striped table-bordered" style="width: 300px;">
  <tr>
    <th style="text-align: center;">Date</th>
    <th style="text-align: center;">Sent</th>
    <th style="text-align: center;">Received</th>
    <th style="text-align: center;">Errors</th>
  </tr>

  <% 3.times do |i| %>
  <% month = (@today - i.months).strftime('%Y-%m') %>
  <tr>
    <td align="center"><%= month %></td>
    <td align="center"><%= number_with_delimiter(@monthly_sent_sms_counts[month].to_i) %></td>
    <td align="center"><%= number_with_delimiter(@monthly_received_sms_counts[month].to_i) %></td>
    <td align="center"><%= number_with_delimiter(@monthly_error_counts[month].to_i) %></td>
  </tr>
  <% end -%>
</table>


<h2>Daily</h2>

<table class="table table-striped table-bordered" style="width: 300px;">
  <tr>
    <th style="text-align: center;">Date</th>
    <th style="text-align: center;">Sent</th>
    <th style="text-align: center;">Received</th>
    <th style="text-align: center;">Errors</th>
  </tr>

  <% 30.times do |i| %>
  <% date = (@today - i).to_s %>
  <tr>
    <td align="center"><%= date %></td>
    <td align="center"><%= number_with_delimiter(@daily_sent_sms_counts[date].to_i) %></td>
    <td align="center"><%= number_with_delimiter(@daily_received_sms_counts[date].to_i) %></td>
    <td align="center"><%= number_with_delimiter(@daily_error_counts[date].to_i) %></td>
  </tr>
  <% end -%>
</table>
</div>

app/views/admin/users.html.erb
<div class='admin-content'>

<form class='form-inline' style='margin: 20px 0'>
  <input type='search' name='name' value='<%= params[:name] %>' placeholder='Username or Email'>
  <button type='submit' class='btn'>Search</button>
</form>

<p>
  <% if @user_search.show_all? %>
    There are <%= pluralize(@users_count, 'user') %>.
  <% else %>
    Found <%= pluralize(@users_count, 'user') %>.
    <% if @users.size > 0 %>
      Showing <%= @offset + 1 %> to <%= @offset + @users.size %>.
    <% end %>
  <% end %>
</p>

<% if @users.present? %>
  <div class='users'>
    <% @users.each do |user| %>
      <div class='user'>
        <%= link_to user.username, admin_user_path(user) %>
      </div>
    <% end %>
  </div>
<% end %>

<ul class='pagination'>
  <% if @offset > 0 %>
    <li><%= link_to 'First', admin_users_path(@user_search.to_params) %></li>
  <% end %>
  <% if @offset - @users.size >= 0 %>
    <li><%= link_to 'Previous', admin_users_path(@user_search.to_params.merge(offset: @offset - @users.size)) %></li>
  <% end %>
  <% if @offset + @users.size < @users_count %>
    <li><%= link_to 'Next', admin_users_path(@user_search.to_params.merge(offset: @offset + @users.size)) %></li>
  <% end %>
</ul>

</div>